FROM codecasts/webserver

ADD . /var/www/html

# utilizando esse comando para construir
# docker build -t codecasts/hello-docker .

# para rodar nosso container
# docker run -it --rm -p 8080:80 codecasts/hello-docker
